### ISSUE TITLE
Issueのテンプレの項目の修正

### ISSUE THREAD

**Issue by akekaneko** [akekaneko/swagger-test#41]
# 問題の背景
Issueのテンプレの項目についてよりよくするため再検討。
解決方法を提案しますが問題あればお知らせください。

# 解決方法
ファイル名:  ISSUE_TEMPLATE.md
修正内容: 以下を項目として盛り込む
---
- 概要(why/what)
- 実行環境
- 再現手順
- 期待される結果
- 解決方法(How)
  - 対象ファイル
  - タスク一覧
- 親課題
- 関連課題
- 担当
  - 修正
  - プルリク担当
- 備考

**Comment by gappoak** [comment]
こめんとてすと
通知てすと

**Comment by gappoak** [comment]
もういっかいてすと

**Comment by akekaneko** [comment]
以下変更してアップしました
修正＞修正担当
プルリク担当＞承認担当
